name: Build grafana custom plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WITH_NODE_VERSION: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.WITH_NODE_VERSION}}
    - name: Check node
      run: node --version
    - name: Check npm
      run: npm --version
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build solution
      run: npm run build
    - name: Upload solution
      uses: actions/upload-artifact@v4.3.1
      with:
        name: build
        path: build
    - name: Create Github release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.run_number }}

