name: Build grafana custom plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WITH_NODE_VERSION: "20.x"

jobs:
    build:
        name: Build plugin
        runs-on: ubuntu-latest
        steps:
        -   name: Setup Node.js environment
            uses: actions/setup-node@v4
            with:
                node-version: ${{env.WITH_NODE_VERSION}}
        -   name: Check node
            run: node --version
        -   name: Check npm
            run: npm --version
        -   name: Checkout code
            uses: actions/checkout@v4
        -   name: Install dependencies
            run: npm install
        -   name: Build solution
            run: npm run build
        -   name: Upload solution
            uses: actions/upload-artifact@v3
            with:
                name: build
                path: build
    release-version: 
        name: Release plugin
        runs-on: ubuntu-latest
        needs: build
        steps: 
        -   name: Download artifact
            uses: actions/download-artifact@v3
            with:
                name: build
        -   name: Test download
            run: ls -R
