name: Build grafana custom plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WITH_NODE_VERSION: "20.x"

jobs:
    build:
        name: Build plugin
        runs-on: ubuntu-latest
        steps:
        -   name: Setup Node.js environment
            uses: actions/setup-node@v4
            with:
                node-version: ${{env.WITH_NODE_VERSION}}
        -   name: Check node
            run: node --version
        -   name: Check npm
            run: npm --version
        -   name: Checkout code
            uses: actions/checkout@v4
        -   name: Install dependencies
            run: npm install
        -   name: Build solution
            run: npm run build
        -   name: Upload solution
            uses: actions/upload-artifact@v3
            with:
                name: build
                path: build
    release-version: 
        name: Release plugin
        runs-on: ubuntu-latest
        needs: build
        steps: 
        -   name: Download artifact
            uses: actions/download-artifact@v3
            with:
                name: build
        -   name: Create Github release
            id: create-new-release
            uses: actions/create-release@v1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with: 
                tag_name: ${{ github.run_number }}
                release_name: ${{ github.run_number }}
        -   name: Upload release
            uses: actions/upload-release-asset@v1
            env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                upload_url: ${{ steps.create-new-release.outputs.upload_url }}
                asset_path: ./build
                asset_name: site-v${{ github.run_number }}.zip
                asset_content_type: application/zip
